version: "3.9"
services:
  digital-library-postgres:
    restart: always
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./init/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5432:5432
  digital-library-server:
    restart: always
    image: nightmare224/digital-library-server:latest
    ports:
      - 5001:5001
    depends_on:
      - digital-library-postgres
  digital-library-client:
    restart: always
    image: nightmare224/digital-library-client:latest
    ports:
      - 5002:5002
    depends_on:
      - digital-library-server